### ISSUE TITLE
Bring back voice experimental spatialisation

### ISSUE THREAD

**Issue by michaellgmichaellg** [Adnezz/VoiceFalloffOverride#3]
This was litterally my MAIN reason to use this amazing mod, the spatialisation.
im either going back to older version hoping it stay working or stop using all of it, i seriously cant disagre more with its removal, it was making a huuuge night and day difference, i have this 1 friend who just reported to this this update happened.
im reverting and never updating until spatialisation is back, sorry but it was half the pog of this mod.
Yes , in my and everyone i made try the mod, was the big fix for everyone voice

**Comment by Adnezz** [comment]
So, I was totally on board with this myself, of course. I found the spatialization parameter, and thought it was the ticket for fixing the issues I was having at the time with picking out the directionality of people's voices.

I thought I'd confirm it by toggling it off, to see the difference. Turn it off, and it's suddenly an awful hard-panned mess, right?

Well, turns out that when you turn off the "voice spatialization fix" it's not actually going back to the default setup. The mod is what was breaking the audio component. But turning it back on would appear to make things correct again.

It creates a strong placebo effect as a result. The sound with the spatialization fix on is the same as if you had never enabled the setting in the first place. It took me months to realize that.

All of that to say,  it doesn't fix anything. It just breaks audio if you turn it on, then off. I won't be re-adding it. 

The main problem with spatialization in VRC currently is that voice locations get desynced from the avatar heads. All you have to do to fix that is to hide and show the avatar.
